# Theme
remote_theme: 'epidrome/cover-card'

# Title and tag line
title: 'Jay Silverman'
description: 'Proven driver of integrating cloud automation, machine learning models, and automated decisions into day-to-day business processes. Personally skilled in cloud architecture, data visualization, and machine learning. Passionate about people development and people leadership.'

# Images
avatar: 'avatar.jpg'
background: 'background.jpg'
favicon: 'favicon.ico'

# Online profiles
linkedin: 'jay-silverman-82776619/'
stack-overflow: '7555028/jay-silverman'
email: 'jason.silverman+viahomepage@gmail.com'
github: 'Techneaux'
#facebook: 'jsilverman'
twitter: 'Jason_Silverman'
#instagram: 'techneaux/'
#pinterest: 'techneaux'
#youtube: ''
#codepen: ''
#steam: ''
#soundcloud: ''
#lastfm: ''
#reddit: ''
#medium:  ''
#tumblr: ''
#weibo: ''
#vk: ''
#blog_url: ''
#messenger: ''

# Advanced settings
plugins:
  - jekyll-remote-theme

theme: jekyll-theme-minimal
