# Theme
remote_theme: 'epidrome/cover-card'

# Title and tag line
title: 'Jay Silverman'
description: 'Data scientist, data-driven environment enabler, operating risk reducer, people leader, aviator, father, and husband.'

# Images
avatar: 'avatar.jpg'
background: 'background.jpg'
favicon: 'favicon.ico'

# Online profiles
facebook: 'https://www.facebook.com/jsilverman'
twitter: 'https://twitter.com/Jason_Silverman'
linkedin: 'https://www.linkedin.com/in/jay-silverman-82776619/'
instagram: 'https://www.instagram.com/techneaux/'
pinterest: 'https://www.pinterest.com/techneaux/'
#youtube: ''
github: 'https://github.com/Techneaux'
#codepen: ''
#steam: ''
#soundcloud: ''
#lastfm: ''
stack-overflow: 'https://stackoverflow.com/users/7555028/jay-silverman'
#reddit: ''
#medium:  ''
#tumblr: ''
#weibo: ''
#vk: ''
#blog_url: ''
email: 'jason.silverman.fromsite@gmail.com'
#messenger: ''

# Advanced settings
plugins:
  - jekyll-remote-theme

theme: jekyll-theme-minimal
